## **MATRIX  OPERATIONS**
### **Addition  and Scalar Multiplication**
#### • The sum of two 𝑚 × 𝑛 matrices 𝐴 and 𝐵 is the 𝑚 × 𝑛 matrix 𝐴 + 𝐵 in which each element is the sum of the corresponding elements of 𝐴 and 𝐵.
#### • The product of a scalar 𝑘 and a matrix 𝐴 is the matrix 𝑘𝐴, in which each element is 𝑘 times the corresponding element of 𝐴.

In [3]:
import numpy as np

In [ ]:
# Example 1: Matrix Addition & Subtraction using numpy
# Given matrices
A = np.array([[1, -8, 3],
              [9, 11, 2],
              [5, -4, 0]])

B = np.array([[-3, 0, 2],
              [12, 7, -1],
              [6, 8, -5]])

C = np.array([[41, -6, 11],
              [-9, -14, 2],
              [0, 10, 4]])

# Find: 2A + B - C
result = 2 * A + B - C

print("2A + B - C =")
print(result)


### **MATRIX MULTIPLICATION**
#### • The product 𝐴𝐵 of two matrices 𝐴 and 𝐵 can be found only if the number of columns of 𝐴 equals the number of rows of 𝐵.
#### • If 𝐴 is an 𝑚 × 𝑛 matrix and 𝐵 is an 𝑛 × 𝑘 matrix, the product 𝐴𝐵 will be an 𝑚 × 𝑘 matrix
#### • If 𝐴 is an 𝑚 × 𝑛 matrix and 𝐵 is an 𝑛 × 𝑚 matrix, the products 𝐴𝐵 and 𝐵𝐴 can both be found. However, 𝐴𝐵 ≠ 𝐵𝐴 in general
#### Example :-Matrix A (2×3)     Matrix B (3×2) 
#### Multiply them: First row, first column:(W)
####                First row, second column:(X)
####                Second row, first column:(Y)
####                Second row, second column:(Z)
#### Resulting Matrix C (2×2):[[W,X],[Y,Z]]

In [7]:
# Matrices
A = np.array([[1, -3],
              [7, 2],
              [-2, 5]])

B = np.array([[1, 0, -1],
              [3, 1, 4]])

# AB → (3x2) × (2x3) = (3x3)
AB = np.dot(A, B)
#behind the scene:-  C=AB
#First row of C:
#𝑐11=(1)(1)+(−3)(3)=1−9=−8
#𝑐12=(1)(0)+(−3)(1)=0−3=−3
#c13 =(1)(−1)+(−3)(4)=−1−12=−13
#Second row of C:
#c21 =(7)(1)+(2)(3)=7+6=13
#c22 =(7)(0)+(2)(1)=0+2=2
#c23 =(7)(−1)+(2)(4)=−7+8=1
#Third row of C:
#c31 =(−2)(1)+(5)(3)=−2+15=13
#c32 =(−2)(0)+(5)(1)=0+5=5
#c33 =(−2)(−1)+(5)(4)=2+20=22

# BA → (2x3) × (3x2) = Not Possible
try:
    BA = np.dot(B, A)
except ValueError as e:
    BA = "Multiplication not possible: " + str(e)

print("AB =")
print(AB)

print("\nBA =")
print(BA)


AB =
[[ -8  -3 -13]
 [ 13   2   1]
 [ 13   5  22]]

BA =
[[ 3 -8]
 [ 2 13]]


### **VECTOR SOLUTIONS**
####  (Behind the scene theory)Steps solving a system of linear equations using matrices  :- Given Matrix Equation:𝐴𝑥⃗=𝑏
####   1)Step 1: Write the Augmented Matrix [𝐴∣𝑏]
####   2)Step 2: Perform Row Operations (Gaussian Elimination)
####   3)Step 3: Solution from RREF
#### Using numpy to solve the system 𝐴𝑥⃗=𝑏 

In [5]:
# Define matrix A
A = np.array([
    [1, -1, 5],
    [3, 3, -1],
    [1, 3, 2]
])

# Define vector b
b = np.array([-6, 10, 5])

# Solve for x using numpy's linear solver
x = np.linalg.solve(A, b)

print("Solution Vector x:")
print(x)


Solution Vector x:
[ 1.  2. -1.]


####  using SymPy to solve the system 𝐴𝑥⃗=𝑏

In [ ]:
from sympy import Matrix, symbols, Eq, solve

# Define variables
x1, x2, x3 = symbols('x1 x2 x3')

# Define the augmented matrix [A | b]
A = Matrix([
    [1, -1, 5],
    [3, 3, -1],
    [1, 3, 2]
])

b = Matrix([-6, 10, 5])

# Form the system of equations
eqs = A * Matrix([x1, x2, x3]) - b

# Solve the system
solution = solve(eqs, (x1, x2, x3))

print("Solution:")
print(solution)


### **Determinant of 2×2 and 3×3 Matrices**
#### Determinant of a 2×2 Matrix: If:𝐴=[[𝑎𝑏][𝑐d]]    Then:det(A)=ad−bc
#### Determinant of a 3×3 Matrix: If A=[[𝑎 𝑏 𝑐 ], [d 𝑒 𝑓 ], [g h 𝑖 ]]
#### Then determinant is:det=det=a(ei−fh)−b(di−fg)+c(dh−eg) 


In [1]:
import numpy as np

# 2x2 matrix
matrix_2x2 = np.array([[3, 8],
                       [4, 6]])

# Determinant
det_2x2 = np.linalg.det(matrix_2x2)
print(f"Determinant of 2x2 matrix: {det_2x2:.0f}")

# 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Determinant
det_3x3 = np.linalg.det(matrix_3x3)
print(f"Determinant of 3x3 matrix: {det_3x3:.0f}")


Determinant of 2x2 matrix: -14
Determinant of 3x3 matrix: -0


### **MULTIPLICATIVE INVERSES** 
#### Definition:→ The inverse of a square matrix 𝐴 is a matrix 𝐴−1 such that:𝐴𝐴−1=𝐴−1𝐴=𝐼  Where I is the Identity Matrix.
#### **Identity Matrix( I )**?→ The identity matrix is a special square matrix in which:All diagonal elements = 1    , All other elements = 0
#### Conditions for Inverse:A matrix 𝐴 has an inverse only if:
####      ->A is a square matrix (same rows & columns)
####      ->det(𝐴)≠0 (Non-zero determinant)     If det⁡(𝐴)=0, inverse does not exist → called Singular Matrix
####      → "det" means **Determinant** of a matrix.We write it as:    det(𝐴)or∣𝐴∣
#### 1)Steps to find 𝐴−1  using Row Operations:
####  Given matrix:𝐴=[[𝑎11 𝑎12 𝑎13] [𝑎21 𝑎22 𝑎23] [𝑎31 𝑎32 𝑎33]]
####  Step 1: Write Augmented Matrix [𝐴∣𝐼] Where  I is the identity matrix of order 3.
####  Step 2: Use Row Operations to convert LHS to Identity Matrix:Operations allowed:→ Swap rows → Multiply or divide a row by a non-zero constant
####  → Add or subtract multiples of one row to another
#### Goal:Convert 𝐴→I  Then RHS becomes 𝐴−1
#### Step 3: Final Augmented Matrix When LHS =𝐼, then RHS =𝐴−1

In [10]:
# Define the matrix A
A = np.array([
    [1, 0, 1],
    [2, -2, -1],
    [3, 0, 0]
])

print("Matrix A:")
print(A)

# Check if Determinant is not zero (Matrix must be invertible)
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

if det_A != 0:
    # Find Inverse of A
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)
else:
    print("Matrix is not invertible")


Matrix A:
[[ 1  0  1]
 [ 2 -2 -1]
 [ 3  0  0]]

Determinant of A: 6.0

Inverse of A:
[[ 0.          0.          0.33333333]
 [-0.5        -0.5         0.5       ]
 [ 1.          0.         -0.33333333]]


### **USING INVERSE TO SOLVE SYSTEM**
#### • Suppose we represent a system of linear equations by 𝐴 റ𝑥 = 𝑏
#### • 𝐴 is an 𝑛 × 𝑛 matrix of coefficients and 𝐴−1 exists
#### • റ𝑥 is an 𝑛 × 1 column vector of variables
#### • 𝑏 is an 𝑛 × 1 column vector of constants
#### • Then റ𝑥 = 𝐴−1𝑏 is the solution to the system
#### • If 𝐴 is invertible, then the equation 𝐴 റ𝑥 = 𝑏 has exactly one solution, namely റ𝑥 = 𝐴−1𝑏