### 1)Find the solution to the system of equations:  x-2y+z=0  , y+2z=5 , x+y+3z=7
#### Solution1:- Step 1: Write the system as a matrix equation:𝐴𝑥=𝑏  A = [[1, -2, 1],[0, 1, 2],[1, 1, 3]] , b = [[0] [5][ 7]]  x= [[x] [y] [z]]
####             Step 2: Solve using row reduction (Gaussian elimination). Row 3: 𝑅3←𝑅3−𝑅1    ,Row 3: 𝑅3←𝑅3−3×𝑅2
####             Step 3: Back substitution.   From Row 3:−4𝑧=−8⇒𝑧=2 find all the values
#### Solution2:- using NumPy

In [1]:
import numpy as np

# Define matrix A and vector b
A = np.array([[1, -2, 1],
              [0, 1, 2],
              [1, 1, 3]])

b = np.array([0, 5, 7])

# Solve for x
x = np.linalg.solve(A, b)

print(x)


[0. 1. 2.]


#### 2)A startup company spent  (dollar)155856   on a combination of 131 tablets, laptops, and desktop computers. Each tablet cost   (dollar)736 , 
#### each laptop cost   (dollar)1377 , and each desktop computer cost   (dollar)1619 . Based on the structure of the company, they purchased twice as many 
#### tablets as laptops. Let  be the number of tablets purchased,  the number of laptops purchased, and  the number of desktops purchased. 
#### How many of each type of equipment did they buy? 

#### Solution1 using numpy 

In [5]:
# Our system:
# x + y + z = 131
# 736x + 1377y + 1619z = 155856
# x - 2y = 0

# Write the coefficients matrix (A) and constants vector (B)
A = np.array([
    [1, 1, 1],
    [736, 1377, 1619],
    [1, -2, 0]
])

B = np.array([131, 155856, 0])

# Solve the system
solution = np.linalg.solve(A, B)

# Display the solution
x, y, z = solution
print(f"Tablets (x) = {int(x)}")
print(f"Laptops (y) = {int(y)}")
print(f"Desktops (z) = {int(z)}")

Tablets (x) = 56
Laptops (y) = 28
Desktops (z) = 46


#### Solution2 using sympy

In [7]:
from sympy import symbols, Eq, solve

# Define the variables
x, y, z = symbols('x y z')

# Equations based on the problem
eq1 = Eq(x + y + z, 131)                      # Total items
eq2 = Eq(736*x + 1377*y + 1619*z, 155856)      # Total cost
eq3 = Eq(x, 2*y)                               # Twice as many tablets as laptops

# Solve the system of equations
solution = solve((eq1, eq2, eq3), (x, y, z))

print(solution)


{x: 56233/1004, y: 56233/2008, z: 94349/2008}


#### 3)A brass manufacturer makes three different type of wholesale brass blocks from copper and zinc according to the following matrix.
####             High brass   Muntz metal      Gilding metal   
####    Copper      65%	            60%             95%
####     Zinc       35%             40%              5%
#### In addition, the demand (in thousands of pounds) from Plant 1 is 11 High Brass, 5 Muntz metal, and 33 Gilding metal, and the demand from Plant 2 is #### 12 High Brass, 3 Muntz metal, and 30 Gilding metal.
#### a) Make a matrix B that contains the blending information in decimal form.	
#### b) Make a matrix D for the demands at each plant. Plant 1 demands should be entered in column 1.	
#### c) Find the matrix product to find each location's need for each type of metal.	
#### d) if the price of zinc is (dollar)0.56 per pound and the price of copper is (dollar)4.04 per pound.


In [15]:
import pandas as pd
from sympy import Matrix

# a) Blending information matrix
B = Matrix([
    [0.65, 0.60, 0.95],
    [0.35, 0.40, 0.05]
])

# b) Demand matrix
D = Matrix([
    [11, 12],
    [5, 3],
    [33, 30]
])

# c) Matrix product
metal_needed = B * D

# d) Cost calculation
copper_price = 4.04
zinc_price = 0.56

# Multiply by 1000 because demands are in thousands
metal_needed_grams = metal_needed * 1000

# Get copper and zinc needs separately
copper_needs = metal_needed_grams.row(0)
zinc_needs = metal_needed_grams.row(1)

# Calculate costs
cost_copper = copper_needs * copper_price
cost_zinc = zinc_needs * zinc_price

# Total cost at each plant
total_cost_each_plant = cost_copper + cost_zinc

# Prepare the data for the table
data = {
    "Metal Type": ["Copper", "Zinc"],
    "Plant 1 (lbs)": [copper_needs[0], zinc_needs[0]],
    "Plant 2 (lbs)": [copper_needs[1], zinc_needs[1]],
    "Plant 1 Cost ($)": [cost_copper[0], cost_zinc[0]],
    "Plant 2 Cost ($)": [cost_copper[1], cost_zinc[1]],
}

# Create the DataFrame
df = pd.DataFrame(data)

# Add the Total Cost row
df.loc["Total"] = df[["Plant 1 Cost ($)", "Plant 2 Cost ($)"]].sum()

# Display the table
print("\nMetal Needs and Costs for Each Plant (in Pounds and Dollars):")
print(df)

# Grand total for both plants
grand_total = sum(total_cost_each_plant)
print(f"\nGrand Total for both Plants: ${float(grand_total):,.2f}")



Metal Needs and Costs for Each Plant (in Pounds and Dollars):
      Metal Type     Plant 1 (lbs)     Plant 2 (lbs)  Plant 1 Cost ($)  \
0         Copper  41500.0000000000  38100.0000000000  167660.000000000   
1           Zinc  7500.00000000000  6900.00000000000  4200.00000000000   
Total        NaN               NaN               NaN  171860.000000000   

       Plant 2 Cost ($)  
0      153924.000000000  
1      3864.00000000000  
Total  157788.000000000  

Grand Total for both Plants: $329,648.00


#### 4)A new website allows consumers to purchase various automobiles via the internet and then take delivery at a local dealer. The following table shows #### the retail price of the cars on the website.
####  	   Brand A   	   Brand B   
#### Compact      	30000  38000 
#### Midsize	42000 47000 
#### Luxury	  63000 54000 
#### Pickup	  70000 72000
#### The dealers make 13% profit per compact car sold, 10% per midsize car, 7% per luxury car, and 19% per pickup truck.
#### Create a matrix to represent the profit (in dollars).
#### How much total profit does the dealer make on 3 Brand A midsize cars?


In [59]:

C = np.array([
    [30000, 38000],  # Compact
    [42000, 47000],  # Midsize
    [63000, 54000],  # Luxury
    [70000, 72000]   # Pickup
])
# Profit Matrix p (Updated Profit % in Decimal)
p = np.array([
    [0.13],  # Compact
    [0.10],  # Midsize
    [0.07],  # Luxury
    [0.19]   # Pickup
])

# Element-wise multiplication
Profit_Dollars = C * p

print("Profit Matrix in Dollars:\n", Profit_Dollars)

price = 42000
profit_percent = 0.10
quantity = 3

total_profit = price * profit_percent * quantity

print("Total Profit on 3 Brand A Midsize cars = $", total_profit)


Profit Matrix in Dollars:
 [[ 3900.  4940.]
 [ 4200.  4700.]
 [ 4410.  3780.]
 [13300. 13680.]]
Total Profit on 3 Brand A Midsize cars = $ 12600.0


#### 5)7x- 19y=3  and -x+ 3y=-3  find coefficient matrix and its inverse and The solution to the system x and y is ?

In [72]:
A = np.array([[7, -19], [-1, 3]])
B = np.array([[3], [-3]])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Coefficient Matrix:\n", A)
print("Inverse of Matrix:\n", A_inv)
print("x =",( X[0][0]))
print("y =", (X[1][0]))

Coefficient Matrix:
 [[  7 -19]
 [ -1   3]]
Inverse of Matrix:
 [[1.5 9.5]
 [0.5 3.5]]
x = -23.999999999999993
y = -8.999999999999996


#### 6)Recardo is trying to plan a meal to meet specific nutritional goals. He wants to prepare a meal containing rice, tofu, and peanuts that will 
#### provide  221 grams of carbohydrates, 176 grams of fat, and 123 grams of protein. He knows that each cup of rice provides 
#### 45 grams of carbohydrates, 0 grams of fat, and 3 grams of protein. Each cup of tofu provides  6 grams of carbohydrates,  9 grams of fat, and 16 grams #### of protein. Finally, each cup of peanuts provides  31 grams of carbohydrates, 70 grams of fat, and  25 grams of protein. 
#### Let r  be the number of cups of rice,  t the number of cups of tofu, and   p the number of cups of peanuts. Set up the system of equations. 
#### Write the equation for the amount of carbohydrates in his meal.
#### How many cups of rice, tofu, and peanuts should he eat?

In [76]:
#45r+6t+31p=221   , 9t+70p=176 , 3r+16t+25p=123
#Coefficient Matrix
A = np.array([
    [45, 6, 31],
    [0, 9, 70],
    [3, 16, 25]
])

# Constants Matrix
B = np.array([221, 176, 123])

# Solve for [r, t, p]
X = np.linalg.solve(A, B)

print("Rice (cups) =", X[0])
print("Tofu (cups) =", X[1])
print("Peanuts (cups) =", X[2])


Rice (cups) = 3.0
Tofu (cups) = 4.0
Peanuts (cups) = 2.0


#### 7)

In [92]:
A = np.array([[7, 3, -2],
              [-5, -3, 4],
              [-3, -1, -5]])

B = np.array([[6, 6, 3],
              [5, 7, 6],
              [-7, 6, -1]])

C = np.array([[-3, -7],
              [5, 7],
              [-1, 6]])

# Find: 2A + B - C
result = A + B 
# Find :B^TC
BT=B.transpose()
#result2 = (BT * C)   	Element-wise only if same shape
result2 = BT@ C 	
print("A + B =")
print(result)
print("BT:",BT)
print(" B^T * C =")
print(result2)

A + B =
[[ 13   9   1]
 [  0   4  10]
 [-10   5  -6]]
BT: [[ 6  5 -7]
 [ 6  7  6]
 [ 3  6 -1]]
 B^T * C =
[[ 14 -49]
 [ 11  43]
 [ 22  15]]


#### 8)find transpose

In [96]:
D=np.array([[9 ,-8, 2 ,7,8],
   [-3 ,5 ,-5 ,-2,0],
   [-7 ,3, -1,-10,1],
    [10,-9,-6,-4,4]])
DT=D.transpose();
print(" D^T: ", DT)

 D^T:  [[  9  -3  -7  10]
 [ -8   5   3  -9]
 [  2  -5  -1  -6]
 [  7  -2 -10  -4]
 [  8   0   1   4]]


#### 9)Solve the system using Cramer's Rule.  -x+6y-5z=21  , -6x+y+4z=-10 , 3x-4y-2z=5 
#### Find the determinant 

In [108]:
A = np.array([
    [-1, 6, -5],
    [-6, 1, 4],
    [3, -4, -2]
])

b=np.array([21,-10,5])
detA = round(np.linalg.det(A), 2)
print("Determinant of A =", detA)

# Matrix for x (replace 1st column with D)
Ax = A.copy()
Ax[:, 0] = b
detAx = round(np.linalg.det(Ax), 2)
print("Det(Ax) =", detAx)

# Matrix for y (replace 2nd column with D)
Ay = A.copy()
Ay[:, 1] = b
detAy = round(np.linalg.det(Ay), 2)
print("Det(Ay) =", detAy)

# Matrix for z (replace 3rd column with D)
Az = A.copy()
Az[:, 2] = b
detAz = round(np.linalg.det(Az), 2)
print("Det(Az) =", detAz)

# Solution using Cramer's Rule
x = detAx / detA
y = detAy / detA
z = detAz / detA

print("\nSolution:")
print("x =", x)
print("y =", y)
print("z =", z)


Determinant of A = -119.0
Det(Ax) = 119.0
Det(Ay) = 0.0
Det(Az) = 476.0

Solution:
x = -1.0
y = -0.0
z = -4.0


#### 10)Find the cofactor of the matrix

In [118]:
import sympy as sp

# Define the Matrix
A = sp.Matrix([[6, 7, -1],
            [2, 6, 0],
            [6, 5, 2]])

print("Matrix A:")
sp.pprint(A)

print("Cofactor Matrix of A:")
C = A.cofactor_matrix()
sp.pprint(C)


Matrix A:
⎡6  7  -1⎤
⎢        ⎥
⎢2  6  0 ⎥
⎢        ⎥
⎣6  5  2 ⎦
Cofactor Matrix of A:
⎡12   -4  -26⎤
⎢            ⎥
⎢-19  18  12 ⎥
⎢            ⎥
⎣ 6   -2  22 ⎦


#### 11)To find the det(A), set up the cofacter expansion of A along row 3:
#### The cofactor expansion along row 3 means we express the determinant as:det(𝐴)=𝑎31⋅𝐶31+𝑎32⋅𝐶32+𝑎33⋅𝐶33+𝑎34⋅𝐶34
#### Where:𝑎31,𝑎32,𝑎33,𝑎34  are the elements of row 3 of matrix A.  𝐶41,𝐶42,𝐶43,𝐶44  are the corresponding cofactors for each element.


In [21]:
from sympy import Matrix

# Define the matrix A
A = Matrix([
    [-4, -4, 5, 3],
    [2, -3, 5, 3],
    [-5, -2, -1, -4],
    [-1, 0, 3, 1]
])

# Pick elements from row 3
row3 = A.row(2)  # Python index 2 → row 3

# Step 1: Compute minors for each element in row 3
# Delete row 3 and respective columns

M31 = A.minor_submatrix(2, 0).det()  # delete row 2, column 0
M32 = A.minor_submatrix(2, 1).det()  # delete row 2, column 1
M33 = A.minor_submatrix(2, 2).det()  # delete row 2, column 2
M34 = A.minor_submatrix(2, 3).det()  # delete row 2, column 3

# Step 2: Signs for cofactors along row 3
# + - + -
signs = [1, -1, 1, -1]

# Step 3: Cofactor expansion
det_A = (row3[0] * signs[0] * M31 +
         row3[1] * signs[1] * M32 +
         row3[2] * signs[2] * M33 +
         row3[3] * signs[3] * M34)

print(f"Minor M31: {M31}")
print(f"Minor M32: {M32}")
print(f"Minor M33: {M33}")
print(f"Minor M34: {M34}")
print(f"Determinant of A (expanded along row 3): {det_A}")


Minor M31: 4
Minor M32: 24
Minor M33: 23
Minor M34: 65
Determinant of A (expanded along row 3): 265


#### 12)Suppose R,M,C,H are square matrices such that det(RM)=24,det(CH)=5, and det(MC)=11. Find det(RM^T) , det(RC^−1 ), det(RMCH)
#### and det(RH)

In [ ]:
#det(A ^T )=det(A)


#### 13)Suppose that A=[[3,-2,2],[0,-5,0],[0,0,5]] The sum of all the eigenvalues of A is   ,The product of all the eigenvalues of A is ?

In [138]:
# Define the matrix
A = np.array([[3, -2,2],
              [0, -5,0],
            [0,0,5]])

# Use numpy's function to find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
# Sum and product of eigenvalues
eigen_sum = np.sum(eigenvalues)
eigen_product = np.prod(eigenvalues)

# Display results
print("Eigenvalues:", eigenvalues)
print("Sum of eigenvalues:", eigen_sum)
print("Product of eigenvalues:", eigen_product)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues: [ 3. -5.  5.]
Sum of eigenvalues: 3.0
Product of eigenvalues: -75.0

Eigenvectors:
[[1.         0.24253563 0.70710678]
 [0.         0.9701425  0.        ]
 [0.         0.         0.70710678]]


#### 14)Find the characteristic polynomial of the matrix  A (using the variable lambda  )

In [1]:
from sympy import symbols, Matrix, eye

# Define the variable
λ = symbols('lambda')

# Define the matrix A
A = Matrix([[5, 0, 2],
            [12, -1, 8],
            [0, 0, 3]])

# Compute the characteristic polynomial: det(A - λI)
char_poly = (A - λ * eye(3)).det()  #eye(3) creates the 3×3 identity matrix.

print("Characteristic Polynomial:")
print(char_poly)



Characteristic Polynomial:
-lambda**3 + 7*lambda**2 - 7*lambda - 15


#### 15)Given the following matrix, A, find each eigenvalue and a corresponding eigenvector.


In [3]:
from sympy import Matrix, symbols, eye, simplify, solve

# Step 1: Define matrix
A = Matrix([
    [-13, 24, -24],
    [-26, 33, -18],
    [-4, 12, -17]
])

# Step 2: Characteristic polynomial
lam = symbols('lambda')
char_poly = simplify((A - lam * eye(3)).det())
print(f"Characteristic Polynomial: {char_poly}")

# Step 3: Solve for eigenvalues (correct way!)
eigenvalues = solve(char_poly, lam)
print(f"Eigenvalues: {eigenvalues}")

# Step 4: Find eigenvectors
for eigenvalue in eigenvalues:
    eig_mat = A - eigenvalue * eye(3)
    null_space = eig_mat.nullspace()
    print(f"Eigenvalue: {eigenvalue}")
    for vec in null_space:
        print(f"Eigenvector: {vec}")


Characteristic Polynomial: -lambda**3 + 3*lambda**2 + 25*lambda - 75
Eigenvalues: [-5, 3, 5]
Eigenvalue: -5
Eigenvector: Matrix([[3/2], [3/2], [1]])
Eigenvalue: 3
Eigenvector: Matrix([[2], [7/3], [1]])
Eigenvalue: 5
Eigenvector: Matrix([[2], [5/2], [1]])
