## MATRIX  OPERATIONS
### Addition  and Scalar Multiplication
#### • The sum of two 𝑚 × 𝑛 matrices 𝐴 and 𝐵 is the 𝑚 × 𝑛 matrix 𝐴 + 𝐵 in which each element is the sum of the corresponding elements of 𝐴 and 𝐵.
#### • The product of a scalar 𝑘 and a matrix 𝐴 is the matrix 𝑘𝐴, in which each element is 𝑘 times the corresponding element of 𝐴.

In [1]:
import numpy as np

In [ ]:
# Example 1: Matrix Addition & Subtraction using numpy
# Given matrices
A = np.array([[1, -8, 3],
              [9, 11, 2],
              [5, -4, 0]])

B = np.array([[-3, 0, 2],
              [12, 7, -1],
              [6, 8, -5]])

C = np.array([[41, -6, 11],
              [-9, -14, 2],
              [0, 10, 4]])

# Find: 2A + B - C
result = 2 * A + B - C

print("2A + B - C =")
print(result)


### MATRIX MULTIPLICATION
#### • The product 𝐴𝐵 of two matrices 𝐴 and 𝐵 can be found only if the number of columns of 𝐴 equals the number of rows of 𝐵.
#### • If 𝐴 is an 𝑚 × 𝑛 matrix and 𝐵 is an 𝑛 × 𝑘 matrix, the product 𝐴𝐵 will be an 𝑚 × 𝑘 matrix
#### • If 𝐴 is an 𝑚 × 𝑛 matrix and 𝐵 is an 𝑛 × 𝑚 matrix, the products 𝐴𝐵 and 𝐵𝐴 can both be found. However, 𝐴𝐵 ≠ 𝐵𝐴 in general
#### Example :-Matrix A (2×3)     Matrix B (3×2) 
#### Multiply them: First row, first column:(W)
####                First row, second column:(X)
####                Second row, first column:(Y)
####                Second row, second column:(Z)
#### Resulting Matrix C (2×2):[[W,X],[Y,Z]]

In [7]:
# Matrices
A = np.array([[1, -3],
              [7, 2],
              [-2, 5]])

B = np.array([[1, 0, -1],
              [3, 1, 4]])

# AB → (3x2) × (2x3) = (3x3)
AB = np.dot(A, B)
#behind the scene:-  C=AB
#First row of C:
#𝑐11=(1)(1)+(−3)(3)=1−9=−8
#𝑐12=(1)(0)+(−3)(1)=0−3=−3
#c13 =(1)(−1)+(−3)(4)=−1−12=−13
#Second row of C:
#c21 =(7)(1)+(2)(3)=7+6=13
#c22 =(7)(0)+(2)(1)=0+2=2
#c23 =(7)(−1)+(2)(4)=−7+8=1
#Third row of C:
#c31 =(−2)(1)+(5)(3)=−2+15=13
#c32 =(−2)(0)+(5)(1)=0+5=5
#c33 =(−2)(−1)+(5)(4)=2+20=22

# BA → (2x3) × (3x2) = Not Possible
try:
    BA = np.dot(B, A)
except ValueError as e:
    BA = "Multiplication not possible: " + str(e)

print("AB =")
print(AB)

print("\nBA =")
print(BA)


AB =
[[ -8  -3 -13]
 [ 13   2   1]
 [ 13   5  22]]

BA =
[[ 3 -8]
 [ 2 13]]
