### Calculate the singular value decomposition of a matrix using the NumPy library:

In [11]:
import numpy as np

# Create a matrix M (3x2 matrix in this case)
M = np.array([[1, 2], [3, 4], [5, 6]])

In [40]:
# Perform SVD on M
U, S, V = np.linalg.svd(M)

# Print the results
# Print the results
print("Matrix M:")
print(M)

print("\nU (left singular vectors):")
print(U)

print("\nS (singular values):")
print(S)

print("\nVt (right singular vectors):")
print(Vt)

Matrix M:
[[1 2]
 [3 4]
 [5 6]]

U (left singular vectors):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

S (singular values):
[9.52551809 0.51430058]

Vt (right singular vectors):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [42]:
# Reconstruct the original matrix
S_matrix = np.zeros_like(M, dtype=float)
S_matrix[:len(S), :len(S)] = np.diag(S)  # Create a diagonal matrix with the singular values
M_reconstructed = np.dot(U, np.dot(S_matrix, V))

print("\nReconstructed Matrix M:")
print(M_reconstructed)



Reconstructed Matrix M:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
